// Render with Asciidoctor

= What's happening here?

== Input

The emojis are categorized in text files in `cats`.

Each text file is a category and a single emoji can be in more than one
category.

Each line of those text files is an emoji followed by space followed by
its name, although this specific name is not used.

The `cats.yml` file maps category IDs (text file names without the
`.txt` extension) to category names. The order of the categories in
`cats.yml` is important as it is the final order of presentation of
those categories in the eventual UI.

`emoji.json` comes from https://github.com/amio/emoji.json[this project]
and associates emojis to their official Unicode names and keywords. I
maintain my own version as, for some reason, the
https://unicode.org/emoji/charts/full-emoji-list.html[official list]
(from which `emoji.json` is created) lacks many
https://emojipedia.org/variation-selector-16/[VS-16] characters. Also, I
added some unofficial keywords to specific emojis.

`with-skin-tone-support.txt` has the same format as a category text
file. It contains the emojis which support emoji skin tone modifiers.

`twemoji-svg` contains the SVG files of the
https://github.com/twitter/twemoji[Twitter emoji] project (see its
license, `twemoji-LICENSE-GRAPHICS`). Each file name is a dash-separated
list of codepoints (hexadecimal) used to create the emoji sequence
followed by `.svg`.

== Output

The `create.py` script creates the required files for the UI in the
specified directory.

From the category files, it knows the supported emojis. It combines this
with the data from `emoji.json` and `with-skin-tone-support.txt` to
create `emojis.json`. This is a map (emoji to info) for each supported
emoji.

From the category files, it also creates `cats.json` which has the same
content as `cats.yml`, but each category entry also has its full list of
emojis.

`create.py` converts the Twemoji SVG files to 32×32 PNG files.

`create.py` also creates `emojis.png` which is a single PNG file
containing all the supported emojis in their 32×32 form. The purpose of
this file is to accelerate the UI, not having to open hundreds of
individual PNG files. It also creates `emojis-png-locations.json` which
maps each emoji to its location (top-left corner), in pixels, within
`emojis.png`.
